-- Ejecutar como administrador de PostgreSQL, revisando los placeholders.
-- Reemplazar NOMBRE_BD, USUARIO_APP y PASSWORD_SEGURA antes de ejecutar.

CREATE DATABASE NOMBRE_BD
    WITH ENCODING 'UTF8'
    TEMPLATE template0;

CREATE ROLE USUARIO_APP
    WITH LOGIN
    PASSWORD 'PASSWORD_SEGURA'
    NOSUPERUSER
    NOCREATEDB
    NOCREATEROLE
    NOREPLICATION;

\connect NOMBRE_BD

CREATE SCHEMA IF NOT EXISTS app AUTHORIZATION USUARIO_APP;
ALTER ROLE USUARIO_APP SET search_path = app, public;

REVOKE ALL ON DATABASE NOMBRE_BD FROM PUBLIC;
GRANT CONNECT ON DATABASE NOMBRE_BD TO USUARIO_APP;
GRANT USAGE, CREATE ON SCHEMA app TO USUARIO_APP;

ALTER DEFAULT PRIVILEGES IN SCHEMA app GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO USUARIO_APP;
ALTER DEFAULT PRIVILEGES IN SCHEMA app GRANT USAGE, SELECT, UPDATE ON SEQUENCES TO USUARIO_APP;
ALTER DEFAULT PRIVILEGES IN SCHEMA app GRANT EXECUTE ON FUNCTIONS TO USUARIO_APP;
